export const mockHiscoreResponse = {
    skills: [
        {
            id: 0,
            name: 'Overall',
            rank: 78286,
            level: 2228,
            xp: 350155825,
        },
        {
            id: 1,
            name: 'Attack',
            rank: 79458,
            level: 99,
            xp: 21037534,
        },
        {
            id: 2,
            name: 'Defence',
            rank: 53390,
            level: 99,
            xp: 19951069,
        },
        {
            id: 3,
            name: 'Strength',
            rank: 75015,
            level: 99,
            xp: 30852600,
        },
        {
            id: 4,
            name: 'Hitpoints',
            rank: 116867,
            level: 99,
            xp: 35183018,
        },
        {
            id: 5,
            name: 'Ranged',
            rank: 154903,
            level: 99,
            xp: 27502842,
        },
        {
            id: 6,
            name: 'Prayer',
            rank: 27429,
            level: 99,
            xp: 13537460,
        },
        {
            id: 7,
            name: 'Magic',
            rank: 69594,
            level: 99,
            xp: 23912339,
        },
        {
            id: 8,
            name: 'Cooking',
            rank: 77845,
            level: 99,
            xp: 14860431,
        },
        {
            id: 9,
            name: 'Woodcutting',
            rank: 111828,
            level: 99,
            xp: 13236327,
        },
        {
            id: 10,
            name: 'Fletching',
            rank: 60226,
            level: 99,
            xp: 13487041,
        },
        {
            id: 11,
            name: 'Fishing',
            rank: 124732,
            level: 99,
            xp: 13041101,
        },
        {
            id: 12,
            name: 'Firemaking',
            rank: 67653,
            level: 99,
            xp: 14106174,
        },
        {
            id: 13,
            name: 'Crafting',
            rank: 58868,
            level: 99,
            xp: 13963216,
        },
        {
            id: 14,
            name: 'Smithing',
            rank: 196089,
            level: 89,
            xp: 5196110,
        },
        {
            id: 15,
            name: 'Mining',
            rank: 49227,
            level: 99,
            xp: 14051688,
        },
        {
            id: 16,
            name: 'Herblore',
            rank: 40589,
            level: 99,
            xp: 13352479,
        },
        {
            id: 17,
            name: 'Agility',
            rank: 202532,
            level: 86,
            xp: 3750415,
        },
        {
            id: 18,
            name: 'Thieving',
            rank: 205777,
            level: 92,
            xp: 6660719,
        },
        {
            id: 19,
            name: 'Slayer',
            rank: 103978,
            level: 99,
            xp: 14465551,
        },
        {
            id: 20,
            name: 'Farming',
            rank: 176294,
            level: 99,
            xp: 13560401,
        },
        {
            id: 21,
            name: 'Runecraft',
            rank: 105400,
            level: 94,
            xp: 7957634,
        },
        {
            id: 22,
            name: 'Hunter',
            rank: 265492,
            level: 85,
            xp: 3447862,
        },
        {
            id: 23,
            name: 'Construction',
            rank: 99655,
            level: 99,
            xp: 13041814,
        },
    ],
    activities: [
        {
            id: 0,
            name: 'League Points',
            rank: -1,
            score: -1,
        },
        {
            id: 1,
            name: 'Deadman Points',
            rank: -1,
            score: -1,
        },
        {
            id: 2,
            name: 'Bounty Hunter - Hunter',
            rank: -1,
            score: -1,
        },
        {
            id: 3,
            name: 'Bounty Hunter - Rogue',
            rank: -1,
            score: -1,
        },
        {
            id: 4,
            name: 'Bounty Hunter (Legacy) - Hunter',
            rank: 164040,
            score: 6,
        },
        {
            id: 5,
            name: 'Bounty Hunter (Legacy) - Rogue',
            rank: 109733,
            score: 6,
        },
        {
            id: 6,
            name: 'Clue Scrolls (all)',
            rank: 54452,
            score: 790,
        },
        {
            id: 7,
            name: 'Clue Scrolls (beginner)',
            rank: 165965,
            score: 27,
        },
        {
            id: 8,
            name: 'Clue Scrolls (easy)',
            rank: 99968,
            score: 65,
        },
        {
            id: 9,
            name: 'Clue Scrolls (medium)',
            rank: 236176,
            score: 57,
        },
        {
            id: 10,
            name: 'Clue Scrolls (hard)',
            rank: 16282,
            score: 454,
        },
        {
            id: 11,
            name: 'Clue Scrolls (elite)',
            rank: 23496,
            score: 118,
        },
        {
            id: 12,
            name: 'Clue Scrolls (master)',
            rank: 35917,
            score: 69,
        },
        {
            id: 13,
            name: 'LMS - Rank',
            rank: 110356,
            score: 737,
        },
        {
            id: 14,
            name: 'PvP Arena - Rank',
            rank: -1,
            score: -1,
        },
        {
            id: 15,
            name: 'Soul Wars Zeal',
            rank: -1,
            score: -1,
        },
        {
            id: 16,
            name: 'Rifts closed',
            rank: 164911,
            score: 174,
        },
        {
            id: 17,
            name: 'Colosseum Glory',
            rank: -1,
            score: -1,
        },
        {
            id: 18,
            name: 'Abyssal Sire',
            rank: 73508,
            score: 378,
        },
        {
            id: 19,
            name: 'Alchemical Hydra',
            rank: -1,
            score: -1,
        },
        {
            id: 20,
            name: 'Amoxliatl',
            rank: -1,
            score: -1,
        },
        {
            id: 21,
            name: 'Araxxor',
            rank: -1,
            score: -1,
        },
        {
            id: 22,
            name: 'Artio',
            rank: -1,
            score: -1,
        },
        {
            id: 23,
            name: 'Barrows Chests',
            rank: 128237,
            score: 415,
        },
        {
            id: 24,
            name: 'Bryophyta',
            rank: -1,
            score: -1,
        },
        {
            id: 25,
            name: 'Callisto',
            rank: -1,
            score: -1,
        },
        {
            id: 26,
            name: "Calvar'ion",
            rank: -1,
            score: -1,
        },
        {
            id: 27,
            name: 'Cerberus',
            rank: 121198,
            score: 523,
        },
        {
            id: 28,
            name: 'Chambers of Xeric',
            rank: 300029,
            score: 6,
        },
        {
            id: 29,
            name: 'Chambers of Xeric: Challenge Mode',
            rank: -1,
            score: -1,
        },
        {
            id: 30,
            name: 'Chaos Elemental',
            rank: 240720,
            score: 6,
        },
        {
            id: 31,
            name: 'Chaos Fanatic',
            rank: 296391,
            score: 7,
        },
        {
            id: 32,
            name: 'Commander Zilyana',
            rank: 167996,
            score: 57,
        },
        {
            id: 33,
            name: 'Corporeal Beast',
            rank: 78821,
            score: 93,
        },
        {
            id: 34,
            name: 'Crazy Archaeologist',
            rank: -1,
            score: -1,
        },
        {
            id: 35,
            name: 'Dagannoth Prime',
            rank: 155337,
            score: 166,
        },
        {
            id: 36,
            name: 'Dagannoth Rex',
            rank: 230055,
            score: 172,
        },
        {
            id: 37,
            name: 'Dagannoth Supreme',
            rank: 154370,
            score: 166,
        },
        {
            id: 38,
            name: 'Deranged Archaeologist',
            rank: -1,
            score: -1,
        },
        {
            id: 39,
            name: 'Duke Sucellus',
            rank: 37163,
            score: 300,
        },
        {
            id: 40,
            name: 'General Graardor',
            rank: 412346,
            score: 14,
        },
        {
            id: 41,
            name: 'Giant Mole',
            rank: 56994,
            score: 674,
        },
        {
            id: 42,
            name: 'Grotesque Guardians',
            rank: -1,
            score: -1,
        },
        {
            id: 43,
            name: 'Hespori',
            rank: 404379,
            score: 20,
        },
        {
            id: 44,
            name: 'Kalphite Queen',
            rank: 202775,
            score: 34,
        },
        {
            id: 45,
            name: 'King Black Dragon',
            rank: 189257,
            score: 180,
        },
        {
            id: 46,
            name: 'Kraken',
            rank: 471230,
            score: 33,
        },
        {
            id: 47,
            name: "Kree'Arra",
            rank: -1,
            score: -1,
        },
        {
            id: 48,
            name: "K'ril Tsutsaroth",
            rank: 150875,
            score: 62,
        },
        {
            id: 49,
            name: 'Lunar Chests',
            rank: -1,
            score: -1,
        },
        {
            id: 50,
            name: 'Mimic',
            rank: 75529,
            score: 3,
        },
        {
            id: 51,
            name: 'Nex',
            rank: 68692,
            score: 220,
        },
        {
            id: 52,
            name: 'Nightmare',
            rank: 85821,
            score: 11,
        },
        {
            id: 53,
            name: "Phosani's Nightmare",
            rank: -1,
            score: -1,
        },
        {
            id: 54,
            name: 'Obor',
            rank: -1,
            score: -1,
        },
        {
            id: 55,
            name: 'Phantom Muspah',
            rank: -1,
            score: -1,
        },
        {
            id: 56,
            name: 'Sarachnis',
            rank: -1,
            score: -1,
        },
        {
            id: 57,
            name: 'Scorpia',
            rank: -1,
            score: -1,
        },
        {
            id: 58,
            name: 'Scurrius',
            rank: -1,
            score: -1,
        },
        {
            id: 59,
            name: 'Skotizo',
            rank: 370233,
            score: 12,
        },
        {
            id: 60,
            name: 'Sol Heredit',
            rank: -1,
            score: -1,
        },
        {
            id: 61,
            name: 'Spindel',
            rank: -1,
            score: -1,
        },
        {
            id: 62,
            name: 'Tempoross',
            rank: -1,
            score: -1,
        },
        {
            id: 63,
            name: 'The Gauntlet',
            rank: -1,
            score: -1,
        },
        {
            id: 64,
            name: 'The Corrupted Gauntlet',
            rank: -1,
            score: -1,
        },
        {
            id: 65,
            name: 'The Hueycoatl',
            rank: -1,
            score: -1,
        },
        {
            id: 66,
            name: 'The Leviathan',
            rank: -1,
            score: -1,
        },
        {
            id: 67,
            name: 'The Whisperer',
            rank: -1,
            score: -1,
        },
        {
            id: 68,
            name: 'Theatre of Blood',
            rank: -1,
            score: -1,
        },
        {
            id: 69,
            name: 'Theatre of Blood: Hard Mode',
            rank: -1,
            score: -1,
        },
        {
            id: 70,
            name: 'Thermonuclear Smoke Devil',
            rank: 230856,
            score: 62,
        },
        {
            id: 71,
            name: 'Tombs of Amascut',
            rank: 120096,
            score: 39,
        },
        {
            id: 72,
            name: 'Tombs of Amascut: Expert Mode',
            rank: 50168,
            score: 98,
        },
        {
            id: 73,
            name: 'TzKal-Zuk',
            rank: 68669,
            score: 1,
        },
        {
            id: 74,
            name: 'TzTok-Jad',
            rank: 142966,
            score: 8,
        },
        {
            id: 75,
            name: 'Vardorvis',
            rank: 97673,
            score: 5,
        },
        {
            id: 76,
            name: 'Venenatis',
            rank: 53801,
            score: 191,
        },
        {
            id: 77,
            name: "Vet'ion",
            rank: -1,
            score: -1,
        },
        {
            id: 78,
            name: 'Vorkath',
            rank: 347601,
            score: 134,
        },
        {
            id: 79,
            name: 'Wintertodt',
            rank: 297847,
            score: 404,
        },
        {
            id: 80,
            name: 'Zalcano',
            rank: -1,
            score: -1,
        },
        {
            id: 81,
            name: 'Zulrah',
            rank: 153119,
            score: 693,
        },
    ],
};
