export const mockHiscoreResponse = {
    skills: [
        {
            id: 0,
            name: 'Overall',
            rank: 79830,
            level: 2223,
            xp: 346656360,
        },
        {
            id: 1,
            name: 'Attack',
            rank: 78278,
            level: 99,
            xp: 21037534,
        },
        {
            id: 2,
            name: 'Defence',
            rank: 52584,
            level: 99,
            xp: 19951069,
        },
        {
            id: 3,
            name: 'Strength',
            rank: 71141,
            level: 99,
            xp: 30852240,
        },
        {
            id: 4,
            name: 'Hitpoints',
            rank: 113651,
            level: 99,
            xp: 35167187,
        },
        {
            id: 5,
            name: 'Ranged',
            rank: 152210,
            level: 99,
            xp: 27455574,
        },
        {
            id: 6,
            name: 'Prayer',
            rank: 26676,
            level: 99,
            xp: 13537456,
        },
        {
            id: 7,
            name: 'Magic',
            rank: 67930,
            level: 99,
            xp: 23828381,
        },
        {
            id: 8,
            name: 'Cooking',
            rank: 76187,
            level: 99,
            xp: 14860431,
        },
        {
            id: 9,
            name: 'Woodcutting',
            rank: 109581,
            level: 99,
            xp: 13235727,
        },
        {
            id: 10,
            name: 'Fletching',
            rank: 59505,
            level: 99,
            xp: 13487041,
        },
        {
            id: 11,
            name: 'Fishing',
            rank: 122926,
            level: 99,
            xp: 13041101,
        },
        {
            id: 12,
            name: 'Firemaking',
            rank: 66299,
            level: 99,
            xp: 14106174,
        },
        {
            id: 13,
            name: 'Crafting',
            rank: 74422,
            level: 99,
            xp: 13604168,
        },
        {
            id: 14,
            name: 'Smithing',
            rank: 192914,
            level: 89,
            xp: 5196110,
        },
        {
            id: 15,
            name: 'Mining',
            rank: 54903,
            level: 99,
            xp: 13789044,
        },
        {
            id: 16,
            name: 'Herblore',
            rank: 39388,
            level: 99,
            xp: 13350859,
        },
        {
            id: 17,
            name: 'Agility',
            rank: 198963,
            level: 86,
            xp: 3742675,
        },
        {
            id: 18,
            name: 'Thieving',
            rank: 201865,
            level: 92,
            xp: 6660699,
        },
        {
            id: 19,
            name: 'Slayer',
            rank: 97339,
            level: 99,
            xp: 14465551,
        },
        {
            id: 20,
            name: 'Farming',
            rank: 200821,
            level: 99,
            xp: 13309264,
        },
        {
            id: 21,
            name: 'Runecraft',
            rank: 129035,
            level: 90,
            xp: 5716496,
        },
        {
            id: 22,
            name: 'Hunter',
            rank: 280595,
            level: 84,
            xp: 3219765,
        },
        {
            id: 23,
            name: 'Construction',
            rank: 97574,
            level: 99,
            xp: 13041814,
        },
    ],
    activities: [
        {
            id: 0,
            name: 'League Points',
            rank: -1,
            score: -1,
        },
        {
            id: 1,
            name: 'Deadman Points',
            rank: -1,
            score: -1,
        },
        {
            id: 2,
            name: 'Bounty Hunter - Hunter',
            rank: -1,
            score: -1,
        },
        {
            id: 3,
            name: 'Bounty Hunter - Rogue',
            rank: -1,
            score: -1,
        },
        {
            id: 4,
            name: 'Bounty Hunter (Legacy) - Hunter',
            rank: 164245,
            score: 6,
        },
        {
            id: 5,
            name: 'Bounty Hunter (Legacy) - Rogue',
            rank: 109891,
            score: 6,
        },
        {
            id: 6,
            name: 'Clue Scrolls (all)',
            rank: 53147,
            score: 790,
        },
        {
            id: 7,
            name: 'Clue Scrolls (beginner)',
            rank: 162076,
            score: 27,
        },
        {
            id: 8,
            name: 'Clue Scrolls (easy)',
            rank: 97872,
            score: 65,
        },
        {
            id: 9,
            name: 'Clue Scrolls (medium)',
            rank: 233579,
            score: 57,
        },
        {
            id: 10,
            name: 'Clue Scrolls (hard)',
            rank: 15762,
            score: 454,
        },
        {
            id: 11,
            name: 'Clue Scrolls (elite)',
            rank: 22663,
            score: 118,
        },
        {
            id: 12,
            name: 'Clue Scrolls (master)',
            rank: 34918,
            score: 69,
        },
        {
            id: 13,
            name: 'LMS - Rank',
            rank: 107582,
            score: 737,
        },
        {
            id: 14,
            name: 'PvP Arena - Rank',
            rank: -1,
            score: -1,
        },
        {
            id: 15,
            name: 'Soul Wars Zeal',
            rank: -1,
            score: -1,
        },
        {
            id: 16,
            name: 'Rifts closed',
            rank: 160348,
            score: 174,
        },
        {
            id: 17,
            name: 'Colosseum Glory',
            rank: -1,
            score: -1,
        },
        {
            id: 18,
            name: 'Abyssal Sire',
            rank: 71704,
            score: 378,
        },
        {
            id: 19,
            name: 'Alchemical Hydra',
            rank: -1,
            score: -1,
        },
        {
            id: 20,
            name: 'Araxxor',
            rank: -1,
            score: -1,
        },
        {
            id: 21,
            name: 'Artio',
            rank: -1,
            score: -1,
        },
        {
            id: 22,
            name: 'Barrows Chests',
            rank: 126838,
            score: 415,
        },
        {
            id: 23,
            name: 'Bryophyta',
            rank: -1,
            score: -1,
        },
        {
            id: 24,
            name: 'Callisto',
            rank: -1,
            score: -1,
        },
        {
            id: 25,
            name: "Calvar'ion",
            rank: -1,
            score: -1,
        },
        {
            id: 26,
            name: 'Cerberus',
            rank: 119189,
            score: 523,
        },
        {
            id: 27,
            name: 'Chambers of Xeric',
            rank: 296526,
            score: 6,
        },
        {
            id: 28,
            name: 'Chambers of Xeric: Challenge Mode',
            rank: -1,
            score: -1,
        },
        {
            id: 29,
            name: 'Chaos Elemental',
            rank: 237309,
            score: 6,
        },
        {
            id: 30,
            name: 'Chaos Fanatic',
            rank: 291488,
            score: 7,
        },
        {
            id: 31,
            name: 'Commander Zilyana',
            rank: 165879,
            score: 57,
        },
        {
            id: 32,
            name: 'Corporeal Beast',
            rank: 78550,
            score: 93,
        },
        {
            id: 33,
            name: 'Crazy Archaeologist',
            rank: -1,
            score: -1,
        },
        {
            id: 34,
            name: 'Dagannoth Prime',
            rank: 153558,
            score: 166,
        },
        {
            id: 35,
            name: 'Dagannoth Rex',
            rank: 227184,
            score: 172,
        },
        {
            id: 36,
            name: 'Dagannoth Supreme',
            rank: 152686,
            score: 166,
        },
        {
            id: 37,
            name: 'Deranged Archaeologist',
            rank: -1,
            score: -1,
        },
        {
            id: 38,
            name: 'Duke Sucellus',
            rank: 35845,
            score: 300,
        },
        {
            id: 39,
            name: 'General Graardor',
            rank: 408552,
            score: 14,
        },
        {
            id: 40,
            name: 'Giant Mole',
            rank: 56197,
            score: 674,
        },
        {
            id: 41,
            name: 'Grotesque Guardians',
            rank: -1,
            score: -1,
        },
        {
            id: 42,
            name: 'Hespori',
            rank: 398653,
            score: 20,
        },
        {
            id: 43,
            name: 'Kalphite Queen',
            rank: 199859,
            score: 34,
        },
        {
            id: 44,
            name: 'King Black Dragon',
            rank: 187563,
            score: 180,
        },
        {
            id: 45,
            name: 'Kraken',
            rank: 464747,
            score: 33,
        },
        {
            id: 46,
            name: "Kree'Arra",
            rank: -1,
            score: -1,
        },
        {
            id: 47,
            name: "K'ril Tsutsaroth",
            rank: 148280,
            score: 62,
        },
        {
            id: 48,
            name: 'Lunar Chests',
            rank: -1,
            score: -1,
        },
        {
            id: 49,
            name: 'Mimic',
            rank: 73888,
            score: 3,
        },
        {
            id: 50,
            name: 'Nex',
            rank: 67521,
            score: 220,
        },
        {
            id: 51,
            name: 'Nightmare',
            rank: 85021,
            score: 11,
        },
        {
            id: 52,
            name: "Phosani's Nightmare",
            rank: -1,
            score: -1,
        },
        {
            id: 53,
            name: 'Obor',
            rank: -1,
            score: -1,
        },
        {
            id: 54,
            name: 'Phantom Muspah',
            rank: -1,
            score: -1,
        },
        {
            id: 55,
            name: 'Sarachnis',
            rank: -1,
            score: -1,
        },
        {
            id: 56,
            name: 'Scorpia',
            rank: -1,
            score: -1,
        },
        {
            id: 57,
            name: 'Scurrius',
            rank: -1,
            score: -1,
        },
        {
            id: 58,
            name: 'Skotizo',
            rank: 365331,
            score: 12,
        },
        {
            id: 59,
            name: 'Sol Heredit',
            rank: -1,
            score: -1,
        },
        {
            id: 60,
            name: 'Spindel',
            rank: -1,
            score: -1,
        },
        {
            id: 61,
            name: 'Tempoross',
            rank: -1,
            score: -1,
        },
        {
            id: 62,
            name: 'The Gauntlet',
            rank: -1,
            score: -1,
        },
        {
            id: 63,
            name: 'The Corrupted Gauntlet',
            rank: -1,
            score: -1,
        },
        {
            id: 64,
            name: 'The Leviathan',
            rank: -1,
            score: -1,
        },
        {
            id: 65,
            name: 'The Whisperer',
            rank: -1,
            score: -1,
        },
        {
            id: 66,
            name: 'Theatre of Blood',
            rank: -1,
            score: -1,
        },
        {
            id: 67,
            name: 'Theatre of Blood: Hard Mode',
            rank: -1,
            score: -1,
        },
        {
            id: 68,
            name: 'Thermonuclear Smoke Devil',
            rank: 227343,
            score: 62,
        },
        {
            id: 69,
            name: 'Tombs of Amascut',
            rank: 118175,
            score: 39,
        },
        {
            id: 70,
            name: 'Tombs of Amascut: Expert Mode',
            rank: 49095,
            score: 98,
        },
        {
            id: 71,
            name: 'TzKal-Zuk',
            rank: 68365,
            score: 1,
        },
        {
            id: 72,
            name: 'TzTok-Jad',
            rank: 141039,
            score: 8,
        },
        {
            id: 73,
            name: 'Vardorvis',
            rank: 94247,
            score: 5,
        },
        {
            id: 74,
            name: 'Venenatis',
            rank: 53200,
            score: 191,
        },
        {
            id: 75,
            name: "Vet'ion",
            rank: -1,
            score: -1,
        },
        {
            id: 76,
            name: 'Vorkath',
            rank: 343702,
            score: 134,
        },
        {
            id: 77,
            name: 'Wintertodt',
            rank: 294152,
            score: 404,
        },
        {
            id: 78,
            name: 'Zalcano',
            rank: -1,
            score: -1,
        },
        {
            id: 79,
            name: 'Zulrah',
            rank: 151804,
            score: 693,
        },
    ],
};
