export const mockHiscoreResponse = {
  name: 'Bald',
  skills: [
    { id: 0, name: 'Overall', rank: 1952851, level: 1228, xp: 35239354 },
    { id: 1, name: 'Attack', rank: -1, level: 1, xp: -1 },
    { id: 2, name: 'Defence', rank: -1, level: 1, xp: -1 },
    { id: 3, name: 'Strength', rank: 827553, level: 96, xp: 9736256 },
    { id: 4, name: 'Hitpoints', rank: 855201, level: 95, xp: 9180591 },
    { id: 5, name: 'Ranged', rank: 1027105, level: 90, xp: 5440060 },
    { id: 6, name: 'Prayer', rank: -1, level: 1, xp: -1 },
    { id: 7, name: 'Magic', rank: 815284, level: 94, xp: 7998100 },
    { id: 8, name: 'Cooking', rank: 1929171, level: 67, xp: 598535 },
    { id: 9, name: 'Woodcutting', rank: -1, level: 1, xp: -1 },
    { id: 10, name: 'Fletching', rank: -1, level: 1, xp: -1 },
    { id: 11, name: 'Fishing', rank: -1, level: 1, xp: -1 },
    { id: 12, name: 'Firemaking', rank: -1, level: 1, xp: -1 },
    { id: 13, name: 'Crafting', rank: 1899742, level: 61, xp: 302454 },
    { id: 14, name: 'Smithing', rank: 1393325, level: 67, xp: 557874 },
    { id: 15, name: 'Mining', rank: -1, level: 1, xp: -1 },
    { id: 16, name: 'Herblore', rank: -1, level: 1, xp: -1 },
    { id: 17, name: 'Agility', rank: -1, level: 1, xp: -1 },
    { id: 18, name: 'Thieving', rank: 1727401, level: 54, xp: 154853 },
    { id: 19, name: 'Slayer', rank: -1, level: 1, xp: -1 },
    { id: 20, name: 'Farming', rank: -1, level: 1, xp: -1 },
    { id: 21, name: 'Runecraft', rank: 1934171, level: 34, xp: 21863 },
    { id: 22, name: 'Hunter', rank: -1, level: 1, xp: -1 },
    { id: 23, name: 'Construction', rank: -1, level: 1, xp: -1 },
    { id: 24, name: 'Sailing', rank: -1, level: 1, xp: 0 },
  ],
  activities: [
    { id: 0, name: 'Grid Points', rank: -1, score: -1 },
    { id: 1, name: 'League Points', rank: -1, score: -1 },
    { id: 2, name: 'Deadman Points', rank: -1, score: -1 },
    { id: 3, name: 'Bounty Hunter - Hunter', rank: -1, score: -1 },
    { id: 4, name: 'Bounty Hunter - Rogue', rank: -1, score: -1 },
    { id: 5, name: 'Bounty Hunter (Legacy) - Hunter', rank: -1, score: -1 },
    { id: 6, name: 'Bounty Hunter (Legacy) - Rogue', rank: -1, score: -1 },
    { id: 7, name: 'Clue Scrolls (all)', rank: -1, score: -1 },
    { id: 8, name: 'Clue Scrolls (beginner)', rank: -1, score: -1 },
    { id: 9, name: 'Clue Scrolls (easy)', rank: -1, score: -1 },
    { id: 10, name: 'Clue Scrolls (medium)', rank: -1, score: -1 },
    { id: 11, name: 'Clue Scrolls (hard)', rank: -1, score: -1 },
    { id: 12, name: 'Clue Scrolls (elite)', rank: -1, score: -1 },
    { id: 13, name: 'Clue Scrolls (master)', rank: -1, score: -1 },
    { id: 14, name: 'LMS - Rank', rank: 143844, score: 712 },
    { id: 15, name: 'PvP Arena - Rank', rank: 1598, score: 3367 },
    { id: 16, name: 'Soul Wars Zeal', rank: -1, score: -1 },
    { id: 17, name: 'Rifts closed', rank: -1, score: -1 },
    { id: 18, name: 'Colosseum Glory', rank: -1, score: -1 },
    { id: 19, name: 'Collections Logged', rank: -1, score: -1 },
    { id: 20, name: 'Abyssal Sire', rank: -1, score: -1 },
    { id: 21, name: 'Alchemical Hydra', rank: -1, score: -1 },
    { id: 22, name: 'Amoxliatl', rank: -1, score: -1 },
    { id: 23, name: 'Araxxor', rank: -1, score: -1 },
    { id: 24, name: 'Artio', rank: -1, score: -1 },
    { id: 25, name: 'Barrows Chests', rank: -1, score: -1 },
    { id: 26, name: 'Bryophyta', rank: -1, score: -1 },
    { id: 27, name: 'Callisto', rank: -1, score: -1 },
    { id: 28, name: "Calvar'ion", rank: -1, score: -1 },
    { id: 29, name: 'Cerberus', rank: -1, score: -1 },
    { id: 30, name: 'Chambers of Xeric', rank: -1, score: -1 },
    { id: 31, name: 'Chambers of Xeric: Challenge Mode', rank: -1, score: -1 },
    { id: 32, name: 'Chaos Elemental', rank: -1, score: -1 },
    { id: 33, name: 'Chaos Fanatic', rank: -1, score: -1 },
    { id: 34, name: 'Commander Zilyana', rank: -1, score: -1 },
    { id: 35, name: 'Corporeal Beast', rank: -1, score: -1 },
    { id: 36, name: 'Crazy Archaeologist', rank: -1, score: -1 },
    { id: 37, name: 'Dagannoth Prime', rank: -1, score: -1 },
    { id: 38, name: 'Dagannoth Rex', rank: -1, score: -1 },
    { id: 39, name: 'Dagannoth Supreme', rank: -1, score: -1 },
    { id: 40, name: 'Deranged Archaeologist', rank: -1, score: -1 },
    { id: 41, name: 'Doom of Mokhaiotl', rank: -1, score: -1 },
    { id: 42, name: 'Duke Sucellus', rank: -1, score: -1 },
    { id: 43, name: 'General Graardor', rank: -1, score: -1 },
    { id: 44, name: 'Giant Mole', rank: -1, score: -1 },
    { id: 45, name: 'Grotesque Guardians', rank: -1, score: -1 },
    { id: 46, name: 'Hespori', rank: -1, score: -1 },
    { id: 47, name: 'Kalphite Queen', rank: -1, score: -1 },
    { id: 48, name: 'King Black Dragon', rank: -1, score: -1 },
    { id: 49, name: 'Kraken', rank: -1, score: -1 },
    { id: 50, name: "Kree'Arra", rank: -1, score: -1 },
    { id: 51, name: "K'ril Tsutsaroth", rank: -1, score: -1 },
    { id: 52, name: 'Lunar Chests', rank: -1, score: -1 },
    { id: 53, name: 'Mimic', rank: -1, score: -1 },
    { id: 54, name: 'Nex', rank: -1, score: -1 },
    { id: 55, name: 'Nightmare', rank: -1, score: -1 },
    { id: 56, name: "Phosani's Nightmare", rank: -1, score: -1 },
    { id: 57, name: 'Obor', rank: -1, score: -1 },
    { id: 58, name: 'Phantom Muspah', rank: -1, score: -1 },
    { id: 59, name: 'Sarachnis', rank: -1, score: -1 },
    { id: 60, name: 'Scorpia', rank: -1, score: -1 },
    { id: 61, name: 'Scurrius', rank: -1, score: -1 },
    { id: 62, name: 'Shellbane Gryphon', rank: -1, score: -1 },
    { id: 63, name: 'Skotizo', rank: -1, score: -1 },
    { id: 64, name: 'Sol Heredit', rank: -1, score: -1 },
    { id: 65, name: 'Spindel', rank: -1, score: -1 },
    { id: 66, name: 'Tempoross', rank: -1, score: -1 },
    { id: 67, name: 'The Gauntlet', rank: -1, score: -1 },
    { id: 68, name: 'The Corrupted Gauntlet', rank: -1, score: -1 },
    { id: 69, name: 'The Hueycoatl', rank: -1, score: -1 },
    { id: 70, name: 'The Leviathan', rank: -1, score: -1 },
    { id: 71, name: 'The Royal Titans', rank: -1, score: -1 },
    { id: 72, name: 'The Whisperer', rank: -1, score: -1 },
    { id: 73, name: 'Theatre of Blood', rank: -1, score: -1 },
    { id: 74, name: 'Theatre of Blood: Hard Mode', rank: -1, score: -1 },
    { id: 75, name: 'Thermonuclear Smoke Devil', rank: -1, score: -1 },
    { id: 76, name: 'Tombs of Amascut', rank: -1, score: -1 },
    { id: 77, name: 'Tombs of Amascut: Expert Mode', rank: -1, score: -1 },
    { id: 78, name: 'TzKal-Zuk', rank: -1, score: -1 },
    { id: 79, name: 'TzTok-Jad', rank: -1, score: -1 },
    { id: 80, name: 'Vardorvis', rank: -1, score: -1 },
    { id: 81, name: 'Venenatis', rank: -1, score: -1 },
    { id: 82, name: "Vet'ion", rank: -1, score: -1 },
    { id: 83, name: 'Vorkath', rank: -1, score: -1 },
    { id: 84, name: 'Wintertodt', rank: -1, score: -1 },
    { id: 85, name: 'Yama', rank: -1, score: -1 },
    { id: 86, name: 'Zalcano', rank: -1, score: -1 },
    { id: 87, name: 'Zulrah', rank: -1, score: -1 },
  ],
}
