export const SKILL_NAMES = {
    Overall: 'overall',
    Attack: 'attack',
    Defence: 'defence',
    Strength: 'strength',
    Hitpoints: 'hitpoints',
    Ranged: 'ranged',
    Prayer: 'prayer',
    Magic: 'magic',
    Cooking: 'cooking',
    Woodcutting: 'woodcutting',
    Fletching: 'fletching',
    Fishing: 'fishing',
    Firemaking: 'firemaking',
    Crafting: 'crafting',
    Smithing: 'smithing',
    Mining: 'mining',
    Herblore: 'herblore',
    Agility: 'agility',
    Thieving: 'thieving',
    Slayer: 'slayer',
    Farming: 'farming',
    Runecraft: 'runecrafting',
    Hunter: 'hunter',
    Construction: 'construction',
};

export const MINIGAME_NAMES = {
    'League Points': 'leaguePoints',
    'Deadman Points': 'deadmanPoints',
    'Bounty Hunter - Hunter': 'bountyHunter',
    'Bounty Hunter - Rogue': 'bountyHunterRogues',
    'Bounty Hunter (Legacy) - Hunter': 'bountyHunterLegacy',
    'Bounty Hunter (Legacy) - Rogue': 'bountyHunterRoguesLegacy',
    'Clue Scrolls (all)': 'clueScrollsAll',
    'Clue Scrolls (beginner)': 'clueScrollsBeginner',
    'Clue Scrolls (easy)': 'clueScrollsEasy',
    'Clue Scrolls (medium)': 'clueScrollsMedium',
    'Clue Scrolls (hard)': 'clueScrollsHard',
    'Clue Scrolls (elite)': 'clueScrollsElite',
    'Clue Scrolls (master)': 'clueScrollsMaster',
    'LMS - Rank': 'lms',
    'PvP Arena - Rank': 'pvpArena',
    'Soul Wars Zeal': 'soulWarsZeal',
    'Rifts closed': 'riftsClosed',
};

export const BOSS_NAMES = {
    'Abyssal Sire': 'abyssalSire',
    'Alchemical Hydra': 'alchemicalHydra',
    Artio: 'artio',
    'Barrows Chests': 'barrowsChests',
    Bryophyta: 'bryophyta',
    Callisto: 'callisto',
    "Calvar'ion": 'calvarion',
    Cerberus: 'cerberus',
    'Chambers of Xeric': 'chambersOfXeric',
    'Chambers of Xeric: Challenge Mode': 'chambersOfXericChallengeMode',
    'Chaos Elemental': 'chaosElemental',
    'Chaos Fanatic': 'chaosFanatic',
    'Commander Zilyana': 'commanderZilyana',
    'Corporeal Beast': 'corporealBeast',
    'Crazy Archaeologist': 'crazyArchaeologist',
    'Dagannoth Prime': 'dagannothPrime',
    'Dagannoth Rex': 'dagannothRex',
    'Dagannoth Supreme': 'dagannothSupreme',
    'Deranged Archaeologist': 'derangedArchaeologist',
    'Duke Sucellus': 'dukeSucellus',
    'General Graardor': 'generalGraardor',
    'Giant Mole': 'giantMole',
    'Grotesque Guardians': 'grotesqueGuardians',
    Hespori: 'hespori',
    'Kalphite Queen': 'kalphiteQueen',
    'King Black Dragon': 'kingBlackDragon',
    Kraken: 'kraken',
    Kreearra: 'kreearra',
    "K'ril Tsutsaroth": 'krilTsutsaroth',
    Mimic: 'mimic',
    Nex: 'nex',
    Nightmare: 'nightmare',
    "Phosani's Nightmare": 'phosanisNightmare',
    Obor: 'obor',
    'Phantom Muspah': 'phantomMuspah',
    Sarachnis: 'sarachnis',
    Scorpia: 'scorpia',
    Skotizo: 'skotizo',
    Spindel: 'spindel',
    Tempoross: 'tempoross',
    'The Gauntlet': 'gauntlet',
    'The Corrupted Gauntlet': 'corruptedGauntlet',
    'The Leviathan': 'leviathan',
    'The Whisperer': 'whisperer',
    'Theatre of Blood': 'theatreOfBlood',
    'Theatre of Blood: Hard Mode': 'theatreOfBloodHardMode',
    'Thermonuclear Smoke Devil': 'thermonuclearSmokeDevil',
    'Tombs of Amascut': 'tombsOfAmascut',
    'Tombs of Amascut: Expert Mode': 'tombsOfAmascutExpertMode',
    'TzKal-Zuk': 'tzKalZuk',
    'TzTok-Jad': 'tzTokJad',
    Vardorvis: 'vardorvis',
    Venenatis: 'venenatis',
    "Vet'ion": 'vetion',
    Vorkath: 'vorkath',
    Wintertodt: 'wintertodt',
    Zalcano: 'zalcano',
    Zulrah: 'zulrah',
};
